### ISSUE TITLE
Hey, where to download REALY_HIFI3D_keypoint and REALY_scan_region？

### ISSUE THREAD

**Issue by drj-123456** [czh-98/REALY#1]

**Comment by czh-98** [comment]
Hi, you need to obtain access to the Headspace dataset first. Please sign the Agreement (https://www-users.cs.york.ac.uk/~nep/research/LYHM/) according to their guideline, after getting the permission, send the reply message to zenghaochai@gmail.com. Then, we will send the download url to you.
