### ISSUE TITLE
train datasets ？

### ISSUE THREAD

**Issue by wangjue-wzq** [czh-98/REALY#3]
What are the training sets for these models as listed on the web page （ https://www.realy3dface.com/  ）?

**Comment by wangjue-wzq** [comment]
I used the pre-trained model in deep3dface （https://github.com/sicxu/Deep3DFaceRecon_pytorch） to test （frontal-view）, and the error is as follows, which is very different from the results given on the web page. What is the reason?

<img width="825" alt="图片" src="https://user-images.githubusercontent.com/32596301/195743558-bead1116-d06b-4b27-9d4c-f06b928d6d1e.png">


`average nmse@nose = 23.167
average nmse@mouth = 20.792
average nmse@forehead = 37.798
average nmse@cheek = 11.772
median nmse@nose = 23.201
median nmse@mouth = 20.776
median nmse@forehead = 37.569
median nmse@cheek = 14.989
standard deviation nmse@nose = 1.858
standard deviation nmse@mouth = 2.579
standard deviation nmse@forehead = 2.841
standard deviation nmse@cheek = 5.433
average nmse@all = 23.382`

<img width="772" alt="图片" src="https://user-images.githubusercontent.com/32596301/195743769-f6299f58-29a8-4742-ba85-316f3b18f5da.png">

**Comment by czh-98** [comment]
> What are the training sets for these models as listed on the web page （ https://www.realy3dface.com/ ）?

We use the official pretrained model provided by these methods. You can refer to these papers for details about experimental settings.

**Comment by czh-98** [comment]
> I used the pre-trained model in deep3dface （[https://github.com/sicxu/Deep3DFaceRecon_pytorch）](https://github.com/sicxu/Deep3DFaceRecon_pytorch%EF%BC%89) to test （frontal-view）, and the error is as follows, which is very different from the results given on the web page. What is the reason?
> 
> <img alt="图片" width="825" src="https://user-images.githubusercontent.com/32596301/195743558-bead1116-d06b-4b27-9d4c-f06b928d6d1e.png">
> 
> `average nmse@nose = 23.167 average nmse@mouth = 20.792 average nmse@forehead = 37.798 average nmse@cheek = 11.772 median nmse@nose = 23.201 median nmse@mouth = 20.776 median nmse@forehead = 37.569 median nmse@cheek = 14.989 standard deviation nmse@nose = 1.858 standard deviation nmse@mouth = 2.579 standard deviation nmse@forehead = 2.841 standard deviation nmse@cheek = 5.433 average nmse@all = 23.382`
> 
> <img alt="图片" width="772" src="https://user-images.githubusercontent.com/32596301/195743769-f6299f58-29a8-4742-ba85-316f3b18f5da.png">

Please check:
1. whether you used a suitable template (i.e., Deep3D.obj) for evaluation. 
2. whether you have disabled the "process=False" for the "trimesh" package since the default setting to save ".obj" will change the topology.
3. whether the predictions are aligned correctly.

For Deep3D, the save process (i.e., 2) might be the reason for such an issue.

**Comment by wangjue-wzq** [comment]
I realize that the unit of nmse is not mm, but the result given is mm. May I ask if there is an accurate conversion relation here?

**Comment by czh-98** [comment]
> I realize that the unit of nmse is not mm, but the result given is mm. May I ask if there is an accurate conversion relation here?

The scales are derived from the original scans in the HeadSpace dataset and our globally aligned scans (see data/metricial_scale.txt). The evaluation of this repo considers the scale automatically.

**Comment by wangjue-wzq** [comment]
Thanks!
